version: 2
jobs:
  build:
    working_directory: ~/cortexinsight/shrine-azure
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/ruby:2.3.7-stretch-node-browsers
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: sudo apt-get update
    - run: sudo apt-get install cmake
    - run: sudo gem install bundler-audit
    - run:
        command: sudo gem install package_cloud brakeman
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: gem install bundler --version 1.15.4
    - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
    - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
        --jobs=4 --retry=3 '
    - save_cache:
      key: v1-dep-{{ .Branch }}-{{ epoch }}
      paths:
      - vendor/bundle
      - ~/virtualenvs
      - ~/.m2
      - ~/.ivy2
      - ~/.bundle
      - ~/.go_workspace
      - ~/.gradle
      - ~/.cache/bower
    - run: echo 'no database'
    - run:
        name: Run Brakeman Security Scanner
        command: brakeman --exit-on-warn -o $CIRCLE_ARTIFACTS/brakeman.html
    - run:
        name: Run Bundle Audit
        command: |
          sudo gem install bundler-audit
          bundle audit update && bundle audit check
    - run:
        name: Publish to Packagecloud
        command: |
          gem build shrine-azure.gemspec
          cp shrine-azure-*.gem $CIRCLE_ARTIFACTS
          package_cloud push cortexinsight/advisory $CIRCLE_ARTIFACTS/shrine-azure-*.gem; true
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results